name: COMP3000

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    container:
     image: node:14

    steps:

      - uses: actions/checkout@v2
      - run: node -v
          
      - name: Run Server
        run: |
         cat server.js
          
      - name: Run Client
        run: |
         cat client.html
         
#       - name: test code
#         run: |
#          cat mytest.js
